# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/okinawa',
                'doc_host': 'https://chen-001.github.io',
                'git_url': 'https://github.com/chen-001/okinawa',
                'lib_path': 'okinawa'},
  'syms': {'okinawa.core': {'okinawa.core.foo': ('core.html#foo', 'okinawa/core.py')}}}
